services:
  - type: web
    name: astrovastu-suvabrata-bharati
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
